Configuration/TCA/Overrides/pages.php
Drop unnecessary variables and always use $GLOBALS['TCA']
=> [TASK] Streamline pages TCA

Classes/EncodeDecoderBase.php
Hello Dmitry
The config for fixedPostVars does not work if I do it according to the old docs.
My config looks like this (its not finished, but at least it works after my change)
```
'fixedPostVars' => array(
'newsDetail' => array(
array(
'GETvar' => 'tx_news_pi1[day]',
),
array(
'GETvar' => 'tx_news_pi1[month]',
),
array(
'GETvar' => 'tx_news_pi1[year]',
),
array(
'GETvar' => 'tx_news_pi1[news]',
'lookUpTable' => array(
'table' => 'tx_news_domain_model_news',
'id_field' => 'uid',
'alias_field' => 'CONCAT(title, "-", uid)',
'addWhereClause' => ' AND NOT deleted',
'useUniqueCache' => 1,
'useUniqueCache_conf' => array(
'strtolower' => 1,
'spaceCharacter' => '-'
),
'languageGetVar' => 'L',
'languageExceptionUids' => '',
'languageField' => 'sys_language_uid',
'transOrigPointerField' => …
```
=> [BUGFIX] Fix ignored config for fixedPostVars

apiwrappers/class.tx_realurl_apiwrapper_6x.php
Hi,
we were able to use the extension with Typo3 6.1.7 only with this patch, as \TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule isn't defined here.
=> apiwrappers Compatibility for Typo3 6.1

Classes/Decoder/UrlDecoder.php, Classes/Encoder/UrlEncoder.php, Configuration/TCA/Overrides/pages.php
I activated the "Exclude from speaking URL" again and implemented it into encoder and decoder.
Since the excluded pages are not the default behavior, it will only search for them when nothing else was found. This should save some time on most page loads.
=> Add "exclude page path" function

Classes/Configuration/AutomaticConfigurator.php
TYPO3 has a new locking API starting from 7.2, the old one is deprecated.
Fixes #22
=> Fixed acquiring lock for AutomaticConfiguration.

Classes/Decoder/UrlDecoder.php
When decoding the URL of a translated page the UrlDecoder looks
for matches in the pages_overlays table. When it finds one, it
returns that overlay's uid as a page id, which is wrong.
It should return the overlay's pid instead.
=> [BUGFIX] Use parent id upon overlay match in decoding process

class.tx_realurl.php
Due there was no possibility to remove the trailing slash, I used the existing config "appendMissingSlash" (which I set to FALSE) to prevent the addition of the slash.
=> [TASK] Respects appendMissingSlash option

composer.json
This ensures that dependencies on these alternative package names can be resolved
in any case.
This is also essential for the TYPO3 composer installers to determine the extension 
name for installation via Composer vcs repository.
=> [TASK] Add "replace" section to composer.json

Classes/Hooks/DataHandler.php
The DataHandler - Hook issued a superfluous DELETE query that used
a non-existent field `uid`.
The call was removed completely since the cache backend handles the same
table entries in the line above.
=> [BUGFIX] Fix DataHandler hook cache handling

Classes/Decoder/UrlDecoder.php
Description/How to reproduce:
* Multilanguage Site
* there is absolutely NO cache entry (tx_realurl_pathcache, tx_realurl_urlcache)
* user get linked from e.g. google on specific page in non default languge
* real url get the right path to page, but save the path in default language (zero)
Result is:
* the saved path is now used to make URL for default language
Example:
http://www.example.com/en/contact.html
switch to default language results to:
http://www.example.com/de/contact.html instead of http://www.example.com/de/kontakt.html
=> fix wrong/default language value on new cache entry

Classes/Decoder/UrlDecoder.php
On decoding, the full scriptpath is handeld by urldecode(). After this,
the slash '/' is used as separator. Doing this way, realurl cannot
handle proper escaped slashes in values.
This patch does the decoding on every value separately as it did realUrl
1.x.
Imagin this scenario:
http://example.com/doc/http%3A%2F%2Fanotherexample.com%2Fapi%2Fdoc%3A123%2F6%2F/
On page doc, the following fixed post vars are configures:
'fixedPostVars' = array(
'presentationConfiguration' => array(
'docid' => array(
'GETvar' => 'tx_example[docid]',
),
),
20 => 'presentationConfiguration',
),
The extensions needs to get the passed URL in variable
tx_example[docid].
=> [BUGFIX] urldecode path segments separately

class.tx_realurl_advanced.php
Pages with title "0" cannot be encoded/decoded (and thus, not viewed) due to a not-type-safe if () comparision.
Our T3 still uses realurl 1.x due to compatibility issues that we haven't gotten around to fixing. Perhaps someone who knows where the relevant code lines are in the 2.x line can quickly insert the fix there, if necessary.
=> Fix pagetitle "0" preventing encoding/decoding.

Classes/Decoder/UrlDecoder.php
On multilanguage websites, the "L" is configured in preVars very often. Because of this, when realurl comes to the most common 404 errors (not existing postVarSet), the preVars are decoded already.
Now, within my ext [pagenotfoundhandling](https://forge.typo3.org/projects/extension-pagenotfoundhandling), I want to be able to deliver the 404 page in the correct language. But when realurl throws the 404, I can't, because there is no "L" in $_GET.
The proposed solution would be a pretty straightforward one, I know. But the problem is gone for low cost and complexity ;-)
What do you think?
=> Make detectedLanguageId available in 404 case

Classes/Encoder/UrlEncoder.php
In File Classes/Encoder/UrlEncoder.php the $insertArray contains the field `tstamp`, but ext_tables.sql doesn't define any `tstamp` field. So I think line 1139 (related to commit ed9086ae) should be deleted.
=> Remove field `tstamp` UrlEncoder.php

Configuration/TCA/Overrides/pages_language_overlay.php
Allow the same `tx_realurl_pathsegment` within the same pid for `pages_language_overlay`.  Different entries will still be different because of their `sys_language_uid`
=> [BUGFIX] Fix #175: Allow same pathsegment for different languages

Classes/Configuration/AutomaticConfigurator.php
When creating the auto configuration for realurl there is a bug in the language select query, where the uid is falsly selected for the language_isocode.
=> Fixed bug in auto configurator, selecting wrong field for lang iso code

Classes/Decoder/UrlDecoder.php
TYPO3 until TYPO3 version 6.2 adds slashes to values of super global $_GET
To avoid slashes added twice, the GeneralUtility::_GET() API method
must be used to obtain GET variable values.
=> Use GeneralUtility::_GET() instead of $_GET

.gitattributes, .gitignore, Tests/Fixtures/realurl.xml, Tests/Functional/Encoder/UrlEncoderTest.php, Tests/Functional/UtilityTest.php, Tests/Unit/RealurlTest.php, composer.json
I created some basic functional testcases for realurl. I've based the configuration for the tests on code from [extension_builder](https://github.com/TYPO3-extensions/extension_builder).
To run the test-cases, you need to install the dependencies using composer:
```
composer install --dev
```
Afterwards, you can run the tests using `composer test`. You need a database user `realurl` without a password to run the tests. Alternatively you can run the following commands:
```
export TYPO3_PATH_WEB=`pwd`/.Build/Web
export typo3DatabaseName='realurl'
export typo3DatabaseHost='127.0.0.1'
export typo3DatabaseUsername='realurl'
export typo3DatabasePassword=''
.Build/bin/phpunit --colors -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
.Build/bin/phpunit --colors -c …
```
=> [FEATURE] Base for Testcases (based on configuration of extension_builder)

Classes/Encoder/UrlEncoder.php
if tx_realurl_pathoverride is set, the url the the very page where it is set is reduced to the value given in tx_realurl_pathsegment. However urls to subpages are still generated with the full url, ignoring tx_realurl_pathoverride. This commit changes that. Also subpages start with the short path given in tx_realurl_pathsegment. 
The UrlDecoder already can handle these urls correctly.
=> [FEATURE] tx_realurl_pathoverride also used for urls of subpages

Classes/Cache/DatabaseCache.php
I don't know if there's a particular reason why crdate is not stored since there is the field in the DB.
I think that crdate is very useful when trying to understand what created a particular entry while debugging Realurl configuration. With crdate you can, by example, go back to the HTTP request from the Apache log.
=> [TASK] Store crdate when a new record is created in tx_realurl_urldata

Resources/Private/Layouts/Backend.html
We install the extension with composer into the typo3/ext folder. Because the path to the assets were hard coded (typo3conf/ext) the assets could not be loaded. With this fix, the path gets generated correct irrespective of the extension installation path.
=> [BUGFIX] Dynamic Asset Path for Backend Module

Classes/EncodeDecoderBase.php
If the url has no query string, removeIgnoredParametersFromURL sets
the variable to null. This causes, that the function
removeIgnoredParametersFromQueryString returns null as well. But if
it returns null instead of empty string, the
removeIgnoredParametersFromURL function appends an senseless
question mark.
=> [BUGFIX] ensure removeIgnoredParametersFromQueryString returns string

Classes/Configuration/ConfigurationReader.php
The documentation says we are not forced to set the rootpage_id in
realurl_conf.php, but can use instead the domain records in typo3 as an
alternative.
However, cross domain links (with typolinkEnableLinksAcrossDomains
enabled) currently work only if each domain has been configured in
realurl_conf.php, with their rootpage_id defined. If using a [_DEFAULT]
config for all domains, cross domain links do not work properly as the
hostname cannot be determined by the setHostnamesForEncoding function.
And then, setRootPageIdFromDomainRecord tries to locate the sys_domain
record, but using the current hostname, not the targeted domain.
=> Crossdomain links when rootpage_id is not defined

Classes/Evaluator/SegmentFieldCleaner.php
this is meant as hint to a behaviour which is confusing our editors currently. If the fill the pathdata-field explicitely they expect the url to be exactly like what they entered. Since in former realurl-version they used the underscore quite often, they still enter underscores. The underscore stays there if they save the page, but in frontend realurl creates a hyphen instead.
We are totally fine with the hyphens but suggest to replace underscores with hpyhens already while saving to avoid confusion.
=> [TASK] Replace underscore with hyphen while saving explicit pathdata in backend

Classes/Cache/DatabaseCache.php
on bigger websites (in our case ~50.000 pages and ~1.000 editors) the sql-statement to limit the number of entries in i.e. pathdata is called every few seconds. Because % 5 means around every fifth's time a new entry is written into that table. From my point of view it would be fitting to do this far more rarely.
It helped in our case to considerably improve DB performance.
% 5000 ist just a suggestion we use currently. Feel free to modify according to your opinion on that.
=> [TASK] reduce amount of calls to limit entries in database tables

Classes/Encoder/UrlEncoder.php
The trimming of multiple slashes at the end of a speaking URL
is now performed before adding remaining URL parameters.
This cleans up multiple slashes at the end of URLs that have
additional GET parameters:
/my/url/with/params///?param1=value1
is now cleaned up and looks like:
/my/url/with/params/?param1=value1
=> [TASK] Trim multiple slashes for URLs with additional params

Classes/Configuration/ConfigurationReader.php
When the `realurl_autoconf.php` file is missing then an exception is thrown:
> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1420480928: RealURL was not able to find the root page id for the domain "www.example.com" | Exception thrown in file /var/www/html/web/typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php in line 496.
The reason is that the hostnames can only be determined after the automatic configuration was performed. That means that the first user after a deployment will see an error page. Setting the hostnames after the automatic configuration should not have any other side effects but should solve this issue.
If you need any further details let me know.
=> Set hostnames after automatic configuration was performed

Classes/Configuration/ConfigurationReader.php
If multiple root pages for a domain are found an exception is thrown.
Enhance the text to inform the user that the issue was multiple root
pages and not anything else.
=> [TASK] Make exception text more descriptive

Classes/Decoder/UrlDecoder.php
When using `redirect_goodUpperDir` handle multiple slashes in a requested URL by replacing all ocurrences of adjacent slashes by a single slash instead of logging a PHP warning and redirecting to the same wrong URL.
`good/good//index.html` redirects to `good/good/index.html`
`good/good//bad///index.html` redirects to `good/good/bad/index.html`, which redirects to `good/good/index.html`
Also search for the bad URL part starting from the back instead of from the front of the string. This lead to wrong URLs if the bad URL part was e.g. a single character which is also part of the valid base URL:
If e.g. the valid URL is 
`http://example.org/en/imprint/index.html`
and 
`http://example.org/en/imprint/in/index.html`
is requested, without the patch the bad part `in` is not replaced where it is …
=> [BUGFIX] 'redirect_goodUpperDir' with multiple slashes or bad parts in good URL (#437)

Classes/Decoder/UrlDecoder.php, Classes/EncodeDecoderBase.php, Classes/Encoder/UrlEncoder.php, Classes/Hooks/DataHandler.php, Tests/Functional/Encoder/UrlEncoderTest.php, ext_conf_template.txt
Hi Dmitry,
this might be a solution to https://github.com/dmitryd/typo3-realurl/issues/199 . The hard coded property `pageTitleFields` is replaced by a configurable list via extension configuration.
If the list is not set, the dafault one will be used.
A new public static method gives access to this list and is also used in the DataHandler hook.
Maybe you find the time for having a look into it ;)
=> [FEATURE] Configurable page title field list like "segTitleFieldList"

Classes/Encoder/UrlEncoder.php
Perhaps i do not get every possible scenario here, but in one scenario this method does not work correctly.
If you have www.domain.de (german) and de.domain.com (english) in one page tree and www.domain.ch (german) and ch.domain.com (english) in another page tree, it is not possible to link from de.domain.com to ch.domain.com. The Link on de.domain.com will always be www.domain.ch, if www.domain.ch is the first domain record in the page tree. 
Because of $this->tsfe->absRefPrefix the urlPrependRegister never gets used an so it can never set the right domain.
Not using absRefPrefix at all is no solution, because it is needed in my scenario. 
As i understand it, the urlPrependRegister is always right, so why bypass it with $this->tsfe->absRefPrefix?
If we just delete it form the url, the …
=> Do not force $this->tsfe->absRefPrefix in postProcessEncodedUrl

Classes/Encoder/UrlEncoder.php, Tests/Functional/Encoder/UrlEncoderTest.php
Encoding of URLs can now be temporarily disabled by setting
a boolean true value to the tx_realurl_disable register.
This can be used for creating a permalink for example:
```
10 = COA
10 {
10 = LOAD_REGISTER
10.tx_realurl_disable = 1
20 = TEXT
20.value = Permalink
20.typolink {
parameter.field = uid
forceAbsoluteUrl = 1
}
30 = RESTORE_REGISTER
}
```
=> [FEATURE] Disable realurl encoding with TSFE register

Classes/Configuration/ConfigurationReader.php
This fixes a bad side effect of the recent commit https://github.com/adrienjacob/typo3-realurl/commit/e1c847d1ef02fcf6ee7f0844cf3c743897423334: pages with mountpoint parameters no longer work in case rootpage_id is not configured, because getDomainNameForPid doesn't take MP params into account. Sorry for not noticing it earlier !
The suggested fix solves this, while still keeping the proper behaviour of cross domain links. However, I wonder whether the whole part here https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Configuration/ConfigurationReader.php#L421-L445 should rather be skipped in case mountpoint params are set, as it's supposed to use only the current domain in this case ?
=> [BUGFIX] Mountpoints, crossdomain links and rootpage_id not set

Classes/Configuration/ConfigurationReader.php
By default, TYPO3 stores the following values in the configuration `cHashExcludedParameters`: `utm_source, utm_medium, utm_campaign, utm_term, utm_content`.
Currently, RealURL accepts any `utm_[a-z]` parameter.
This commit sets this list in the RealURL ignored get-parameters list, to prevent any `utm_*` parameter that is not supported from being added.
=> [BUGFIX] Fix ignored `utm_*` get-parameters list

ext_tables.sql
When using Percona XtraDB Cluster in strict mode = ENFORCING or MASTER (highly recommanded) it's not permit to have a table without a primary key. Then I'm proposing to add a primary key for the table tx_realurl_uniqalias_cache_map.
=> A primary key for the table tx_realurl_uniqalias_cache_map

Classes/Hooks/DataHandler.php
Don't cast the field-name to an integer. Otherwise path-segments of translated records (non-pages) will not be automatically updated if the record is changed.
=> [BUGFIX] Removed wrong typecast

Classes/Cache/DatabaseCache.php
In the limitTableRecords function a periodic cleanup is triggered, that
comes down to a select and delete function, which is run inside an
explicit transaction. Given that we only have a single data modifying
operation that doesn't seem to serve any purpose.
The reason for our interest in this change, is that we're seeing some heavy periodic locking activity hitting the tx_realurl_urldata table, and the cause seems to be this transaction.
It's important to remember that, when using MySQL and starting a transaction, you're by default setting the database to use the "Repeatable Read" isolation mode. Using "repeatable read" means that any select you perform will set locks for the rows you access, until the transaction is completed.
I'll note that in other parts of the code you're using …
=> Remove pointless explicit transaction

Classes/Utility.php
This is needed for compatibility with TYPO3 v9.
=> [BUGFIX] Use makeInstance instead of $GLOBALS for CharsetConverter

ext_localconf.php
#606 
The change to `require_once` in 2.3.2 breaks TYPO3 8 (and older) setups where `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']` is accessed for example in `typo3conf/RealUrlConfiguration.php` and results in `null` and not the expected `Array`.
Before this it did work. 2.3.1 was still fine.
=> [BUGFIX] use requireOnce of the GeneralUtility to load the default config

composer.json, ext_emconf.php
I cannot see any reason why realurl is not compatible with PHP 7.2. We are using it with PHP 7.2 and we could not see any problems so far.
=> Allow PHP 7.2

Classes/Decoder/UrlDecoder.php
Correct the merge order of variables from $_GET and GETvars from domains configuration. $_GET must have the higher priority compared to GETvars.
The wrong order was introduced in b0945b0. I think it was not by intention, but a mistake, because there is already comment _"Overwrite with $\_GET-params that $\_GET-parmas have a "higher" priority"_.
Two examples where the wrong order causes problems:
1.) Language switcher in View-Module (introduced with 7.x):
It uses non-RealURL-encoded links using the current domain and adds the L-parameter with the selected sys_language_uid to preview the page in the respective language (see [code](https://github.com/TYPO3/TYPO3.CMS/blob/a4cd49c3307d2953ef54134406d9ce0c823730b2/typo3/sysext/viewpage/Classes/Controller/ViewModuleController.php#L326)). This …
=> [BUGFIX] Ensure higher priority of $_GET-vars

Classes/Decoder/UrlDecoder.php
http://example.org/bad1/bad2/bad3/ and http://example.org/good/bad1/bad2/bad3/ creates to a wrong redirect.
If `$pathSegments` contains more than one element the operation `$nonProcessedArray = array($postVarSetKey) + $pathSegments` leads to only the last element being appended to the `$badPathPart`, e.g. http://example.org/bad1/bad2/bad3/ leads to `$badPathPart = 'bad1/bad3';` which will not be found in `$this->originalPath`. `$nonProcessedArray = array_merge(array($postVarSetKey), $pathSegments)` correctly identifies `$badPathPart ='bad1/bad2/bad3';` creating the correct redirect.
Currently the badPathPart handling for two or more adjacent slashes is triggered even if there is only one slash, using `strpos($badPathPart, '//')` yields the correct behaviour.
=> Fix redirect_goodUpperDir bugs

composer.json, ext_emconf.php
According to PHPStan and to our tests realurl has no compatiblity issues with PHP 7.3
=> [TASK] Mark as compatible with PHP 7.3

composer.json
By the removal of the deprecated replace entry with the commit https://github.com/dmitryd/typo3-realurl/commit/76cc5e73be6ed40d778e654007d49b4036acf121 the extension key is also changed for composer based installs because the key was resolved from this line see https://github.com/TYPO3/CmsComposerInstallers/blob/master/src/Plugin/Util/ExtensionKeyResolver.php#L37. Therefor a new extra option was introduced by the CmsComposerInstallers which is also the recommended way by the core to define a extension key see https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#minimal-composer-json.
=> [TASK] Provide the extension key for composer based installs

ext_localconf.php
Currently the default logging cannot be overridden in the `AdditionalConfiguration.php`.
=> [BUGFIX] Fix #672: Allow overriding default logging configuration
