dmitryd/typo3-realurl

- Classes/Decoder/UrlDecoder.php
- Classes/EncodeDecoderBase.php
- Classes/Encoder/UrlEncoder.php
This corrects some minor bugs.
> Minor fixes

- Classes/EncodeDecoderBase.php
- composer.json
- ext_emconf.php
- ext_localconf.php
See separate commits for more information
> [TASK] Added simple flow for TYPO3 7.4 or higher

- Classes/Decoder/UrlDecoder.php
Adds a check to ensure that we do not call a member function on NULL in
any case.
> [BUGFIX] Fix method call on null

- Classes/Decoder/UrlDecoder.php
- Classes/Encoder/UrlEncoder.php
- ext_emconf.php
The typos in Classes were found and fixed by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix some typos

- Classes/Decoder/UrlDecoder.php
User is not yet initiated at this stage
Resolves: #50
> [BUGFIX] Ignore fe_group on enableFields()

- Classes/Decoder/UrlDecoder.php
Do not initialize realurl if it is not necessary at all. (#72)
> [BUGFIX] Detect non-speaking URLs on decode

- Classes/Utility.php
> [TASK] Make strtolower optional for convertToSafeString

- Classes/Configuration/ConfigurationReader.php
We needed a simple hook to modify the configuration
> [FEATURE] added a hook for post-processing the configuration 

- Classes/Configuration/ConfigurationReader.php
> [FEATURE] Add ke_search extension to banUrlsRegExp.

- ext_localconf.php
Replaced ::class usage with class-names as strings
> [BUGFIX] Fixed usage of ::class in ext_localconf.php (Fixes #212)

- Classes/Configuration/AutomaticConfigurator.php
> [BUGFIX] Fix invalid SQL in language selection logic

- Configuration/TCA/Overrides/pages.php
> [BUGFIX] Show path override fields for doktype=3 as well

- Classes/Configuration/ConfigurationReader.php
- Classes/Decoder/UrlDecoder.php
see #205 
Please apologize that messy Pull Request 😓
> [FEATURE] enable nested GET-params when decoding _DOMAIN configurations

- Classes/Encoder/UrlEncoder.php
> [TASK] Checks that encodeUrlParameterBlockUsingUserFunc() returns a valid value

- class.ext_update.php
> Missing space in "DROP TABLE"

- ext_tables.sql
Hello Dmitry,
You changed table name but not in comment.
> Fix table name in comment

- Configuration/TCA/Overrides/pages.php
This adds palette options for mount points in the back-end ("exclude from", "speaking url", "override"...)
> Add palette options for mount points

- Classes/Decoder/UrlDecoder.php
- Classes/EncodeDecoderBase.php
- Classes/Hooks/DataHandler.php
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix some typos in comments

- Resources/Private/Language/locallang.xlf
Changed "mount moint" to mount _point_
> Fixed a typo

- Classes/Decoder/UrlDecoder.php
- Classes/Encoder/UrlEncoder.php
> [FEATURE] Add option to enforce full evaluation of fixedPostVarSets

- Classes/Encoder/UrlEncoder.php
Fixes the issue mentioned in #415 by correcting the check to build the query
> [BUGFIX] Fixes fetching of aliases from the cache as well as un-expiring specifically requested aliases - fix #415

- ext_emconf.php
> [TASK] Raise allowed php version

- Classes/Encoder/UrlEncoder.php
> [BUGFIX] Don't re-use unique aliases that are still active

- Configuration/TCA/tx_realurl_pathdata.php
- Configuration/TCA/tx_realurl_uniqalias.php
- Configuration/TCA/tx_realurl_urldata.php
Removes those annoying TCA warnings in depr log and install tool
gRTz 
Jacco van der Post
> [BUGFIX] Fix #479: update TCA datetime fields

- Classes/Decoder/UrlDecoder.php
This can be used in decode hooks.
Fixes #566
> [TASK] Add public getter for rootpage ID

- Classes/Encoder/UrlEncoder.php
> [BUGFIX] shortcuts need to redirect to encoded URLs

- Classes/Decoder/UrlDecoder.php
> [BUGFIX] Restore ignored params before redirect for missing slash

- Classes/Utility.php
Sometimes string conversion needs to be processed differently (e.g. for suomi URLs). This commit adds a hook to enabling to do so.
> [FEATURE] Add post-processing hook for convertToSafeString method

- Classes/Utility.php
As we discussed in slack, I added the pre-processing hook in convertToSafeString
> Add pre-processing hook in convertToSafeString

- Classes/Configuration/ConfigurationReader.php
- ext_localconf.php
> Ignore new Facebook Urlparameter fbclid
